"""
Title resolution: get_session_title_from_jsonl(), _extract_message_text(),
_clean_synthetic_user_text().

This is the most-patched area of the codebase -- 0.1.1 (list-shaped
content), 0.1.3 (custom-title / last-wins), 0.2.1 (<local-command-caveat>),
0.3.2 (<local-command-stdout>). Every one of those regressions gets a case
here.
"""
import tempfile
import unittest
from pathlib import Path

from tests.helpers import cc, write_jsonl


class ExtractMessageTextTests(unittest.TestCase):
    def test_plain_string_is_returned_as_is(self):
        self.assertEqual(cc._extract_message_text("hello"), "hello")

    def test_blank_string_returns_none(self):
        self.assertIsNone(cc._extract_message_text("   "))

    def test_list_with_text_block_extracts_it(self):
        content = [{"type": "text", "text": "hello"}, {"type": "tool_use", "id": "x"}]
        self.assertEqual(cc._extract_message_text(content), "hello")

    def test_list_with_multiple_text_blocks_joins_them(self):
        content = [{"type": "text", "text": "hello"}, {"type": "text", "text": "world"}]
        self.assertEqual(cc._extract_message_text(content), "hello world")

    def test_list_with_only_tool_blocks_returns_none(self):
        content = [{"type": "tool_result", "content": "some output"}]
        self.assertIsNone(cc._extract_message_text(content))

    def test_non_str_non_list_content_returns_none(self):
        self.assertIsNone(cc._extract_message_text(42))
        self.assertIsNone(cc._extract_message_text(None))
        self.assertIsNone(cc._extract_message_text({"type": "text"}))


class CleanSyntheticUserTextTests(unittest.TestCase):
    """
    Regression coverage for the two wrapper tags that were leaking through
    as raw session titles: <local-command-caveat> (0.2.1) and
    <local-command-stdout> (0.3.2).
    """

    def test_local_command_caveat_is_skipped(self):
        text = ("<local-command-caveat>Caveat: The messages below were "
                "generated by the user while running local commands.</local-command-caveat>")
        self.assertIsNone(cc._clean_synthetic_user_text(text))

    def test_local_command_stdout_is_skipped(self):
        text = ("<local-command-stdout>That session is still running as a "
                "background agent.</local-command-stdout>")
        self.assertIsNone(cc._clean_synthetic_user_text(text))

    def test_command_with_args_extracts_name_and_args(self):
        text = ("<command-message>loop</command-message>\n"
                 "<command-name>/loop</command-name>\n"
                 "<command-args>migrate the thing</command-args>")
        self.assertEqual(cc._clean_synthetic_user_text(text), "/loop: migrate the thing")

    def test_command_with_empty_args_is_skipped(self):
        text = ("<command-name>/clear</command-name>\n"
                 "<command-message>clear</command-message>\n"
                 "<command-args></command-args>")
        self.assertIsNone(cc._clean_synthetic_user_text(text))

    def test_command_args_without_a_name_tag_still_extracts_args(self):
        text = "<command-message>x</command-message>\n<command-args>just the args</command-args>"
        self.assertEqual(cc._clean_synthetic_user_text(text), "just the args")

    def test_plain_text_passes_through_unchanged(self):
        self.assertEqual(
            cc._clean_synthetic_user_text("ok get up to speed with the project"),
            "ok get up to speed with the project",
        )

    def test_leading_whitespace_before_a_wrapper_tag_is_still_detected(self):
        text = "   <local-command-caveat>noise</local-command-caveat>"
        self.assertIsNone(cc._clean_synthetic_user_text(text))


class GetSessionTitleFromJsonlTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.path = Path(self.tmp.name) / "session.jsonl"

    def test_plain_string_user_message_becomes_the_title(self):
        write_jsonl(self.path, [
            {"type": "user", "message": {"role": "user", "content": "hello world"}},
        ])
        title, authoritative = cc.get_session_title_from_jsonl(self.path)
        self.assertEqual(title, "hello world")
        self.assertFalse(authoritative)

    def test_list_shaped_content_becomes_the_title(self):
        # Regression: 0.1.1 -- content as [{"type": "text", ...}] used to
        # fall all the way through to the raw UUID.
        write_jsonl(self.path, [
            {"type": "user", "message": {"role": "user",
             "content": [{"type": "text", "text": "hi there"}]}},
        ])
        title, _ = cc.get_session_title_from_jsonl(self.path)
        self.assertEqual(title, "hi there")

    def test_custom_title_wins_over_first_message(self):
        write_jsonl(self.path, [
            {"type": "user", "message": {"role": "user", "content": "first message"}},
            {"type": "custom-title", "customTitle": "renamed title"},
        ])
        title, authoritative = cc.get_session_title_from_jsonl(self.path)
        self.assertEqual(title, "renamed title")
        self.assertTrue(authoritative)

    def test_last_custom_title_wins_over_an_earlier_one(self):
        # Regression: 0.1.3 -- title can be renamed mid-conversation; the
        # code used to return on the first match instead of the last.
        write_jsonl(self.path, [
            {"type": "custom-title", "customTitle": "first name"},
            {"type": "custom-title", "customTitle": "second name"},
        ])
        title, _ = cc.get_session_title_from_jsonl(self.path)
        self.assertEqual(title, "second name")

    def test_summary_used_when_no_custom_title_present(self):
        write_jsonl(self.path, [
            {"type": "summary", "summary": "a summary title"},
            {"type": "user", "message": {"role": "user", "content": "hello"}},
        ])
        title, authoritative = cc.get_session_title_from_jsonl(self.path)
        self.assertEqual(title, "a summary title")
        self.assertTrue(authoritative)

    def test_custom_title_wins_over_summary(self):
        write_jsonl(self.path, [
            {"type": "summary", "summary": "a summary title"},
            {"type": "custom-title", "customTitle": "a custom title"},
        ])
        title, _ = cc.get_session_title_from_jsonl(self.path)
        self.assertEqual(title, "a custom title")

    def test_local_command_caveat_is_skipped_for_the_real_first_message(self):
        # Regression: 0.2.1
        write_jsonl(self.path, [
            {"type": "user", "message": {"role": "user",
             "content": "<local-command-caveat>noise</local-command-caveat>"}},
            {"type": "user", "message": {"role": "user", "content": "the real first message"}},
        ])
        title, _ = cc.get_session_title_from_jsonl(self.path)
        self.assertEqual(title, "the real first message")

    def test_local_command_stdout_is_skipped_for_the_real_first_message(self):
        # Regression: 0.3.2
        write_jsonl(self.path, [
            {"type": "user", "message": {"role": "user",
             "content": "<local-command-stdout>still running as a background agent</local-command-stdout>"}},
            {"type": "user", "message": {"role": "user", "content": "the real first message"}},
        ])
        title, _ = cc.get_session_title_from_jsonl(self.path)
        self.assertEqual(title, "the real first message")

    def test_loop_command_invocation_extracts_a_clean_snippet(self):
        write_jsonl(self.path, [
            {"type": "user", "message": {"role": "user", "content":
             "<command-message>loop</command-message>\n<command-name>/loop</command-name>\n"
             "<command-args>migrate dpx_yolo_reader - test GUI live</command-args>"}},
        ])
        title, _ = cc.get_session_title_from_jsonl(self.path)
        self.assertEqual(title, "/loop: migrate dpx_yolo_reader - test GUI live")

    def test_only_synthetic_content_falls_back_to_uuid_stem(self):
        write_jsonl(self.path, [
            {"type": "user", "message": {"role": "user",
             "content": "<local-command-caveat>noise</local-command-caveat>"}},
            {"type": "user", "message": {"role": "user",
             "content": "<local-command-stdout>still noise</local-command-stdout>"}},
        ])
        title, authoritative = cc.get_session_title_from_jsonl(self.path)
        self.assertEqual(title, "session")  # jsonl.stem
        self.assertFalse(authoritative)

    def test_empty_file_falls_back_to_uuid_stem(self):
        self.path.write_text("", encoding="utf-8")
        title, authoritative = cc.get_session_title_from_jsonl(self.path)
        self.assertEqual(title, "session")
        self.assertFalse(authoritative)

    def test_long_first_message_is_truncated_with_ellipsis(self):
        write_jsonl(self.path, [
            {"type": "user", "message": {"role": "user", "content": "x" * 200}},
        ])
        title, _ = cc.get_session_title_from_jsonl(self.path)
        self.assertTrue(title.endswith("..."))
        self.assertEqual(len(title), 123)  # 120 chars + "..."

    def test_newlines_in_first_message_are_collapsed_to_spaces(self):
        write_jsonl(self.path, [
            {"type": "user", "message": {"role": "user", "content": "line one\nline two"}},
        ])
        title, _ = cc.get_session_title_from_jsonl(self.path)
        self.assertEqual(title, "line one line two")


if __name__ == "__main__":
    unittest.main()
